export const salesData = [
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },

  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "Sam John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
  {
    course: "Complete Affiliate Mastery Course",
    date: new Date(2024, 6, 4),
    buyer: "David John",
    amount: 12,
    commission: 6,
  },
];
